export enum FIRST_BYTES_CODES {
  SIMPLE_STRING = "+",
  SIMPLE_ERROR = "-",
  INTEGER = ":",
  BULK_STRING = "$",
  ARRAY = "*",
  NULL = "_",
  BOOLEAN = "#",
  DOUBLE = ",",
  BIG_NUMBER = "(",
  BULK_ERROR = "!",
  VERBATIM_STRING = "=",
  MAP = "%",
  SET = "~",
  PUSH = ">",
}
